# --- DB PATH ---
database_in=file:/var/lib/aide/aide.db.gz
database_out=file:/var/lib/aide/aide.db.new.gz
gzip_dbout=yes

# --- RULE DEFINITION---
SECURE = p+i+n+u+g+s+m+c+sha256+sha512

# --- SSH FILES ---
/etc/ssh/sshd_config$   SECURE
/etc/ssh/ssh_config$    SECURE
/etc/ssh/.*\.pub$       SECURE
/etc/ssh/ssh_host.* SECURE

# --- Sysctl FILES ---
/etc/sysctl.conf$       SECURE
/etc/sysctl.d/.* SECURE
